bomberos/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import *
from bomberos.views import *
from bomberos.models import *
#from django.views.generic import TemplateView
#from django.contrib.auth.decorators import login_required
from exportar import exportarCSV,exportar_xls,exportar_xls_cadetes,exportar_xls_bomberos

urlpatterns = patterns('',
        #url(r'^$','bomberos.views.principal'),
        url(r'^$', PrincipalView.as_view()),

        # Listados
        url(r'bomberos/$', ListBomberosView.as_view(),name='bomberos_list'),
        url(r'asociaciones/$', ListAsociacionesView.as_view(),name='asociaciones_list'),
        url(r'pb/$', ListPadronBView.as_view(),name='pbomb_list'),
        url(r'padron_cadetes/$', ListPadronCView.as_view(),name='padron_cadetes_list'),
        url(r'unidades/$', ListUnidadesView.as_view(),name='unidades_list'),
        url(r'personas/$', personas,name='personas_list'),

        #ABM Bomberos bomberos/<id_asociac>/<accion>
        url(r'bomberos/(?P<asociacion_id>\d{1,5})/$', ListBomberosView.as_view(),name='bomberos_list'),
        #url(r'bomberos/(?P<pk>\d{1,5})/detalle/$',  BomberoDetailView.as_view(), name='bombero_detail'),
        url(r'bomberos/(?P<pk>\d{1,5})/detalle/$',  detalle_Bombero, name='bombero_detail'),
        url(r'bomberos/(?P<asociacion_id>\d{1,5})/agregar/$', BomberoCreateView.as_view(), name='bombero_create'),
        url(r'bomberos/(?P<asociacion_id>\d{1,5})/editar/(?P<pk>\d{1,5})/$', BomberoUpdateView.as_view(), name='bombero_update'),
        url(r'bomberos/(?P<pk>\d{1,5})/baja/$', darBajaBombero, name='bombero_baja'),
        url(r'bomberos/(?P<asociacion_id>\d{1,5})/exportar/CSV/$', exportarCSV,{"modelo": Bombero}, name='bombero_exportarCSV'),
        url(r'bomberos/(?P<asociacion_id>\d{1,5})/exportar/XLS/$',exportar_xls,{"modelo": Bombero}, name='exportar_xls_bomberos'),

        #ABM Asociaciones
        url(r'asociaciones/(?P<asociacion_id>\d{1,5})/$', ListAsociacionesView.as_view(),name='asociaciones_list'),
        url(r'asociaciones/(?P<pk>\d{1,5})/detalle/$',  detalle_Asociacion, name='asociacion_detail'),
        url(r'asociaciones/agregar/$', AsociacionCreateView.as_view(), name='asociacion_create'),
        url(r'asociaciones/(?P<pk>\d{1,5})/editar/$', AsociacionUpdateView.as_view(), name='asociacion_update'),
        #url(r'asociaciones/(?P<pk>\d{1,5})/baja/$', darBaja, name='asociacion_baja'),
        url(r'asociaciones/(?P<asociacion_id>\d{1,5})/exportar/CSV/$', exportarCSV,{"modelo": Asociacion}, name='asociacion_exportarCSV'),
        url(r'asociaciones/(?P<asociacion_id>\d{1,5})/exportar/XLS/$', exportar_xls,{"modelo": Asociacion}, name='asociacion_exportarXLS'),

        #ABM Unidades
        url(r'unidades/(?P<asociacion_id>\d{1,5})/$', ListUnidadesView.as_view(),name='unidades_list'),
        url(r'unidades/(?P<pk>\d{1,5})/detalle/$',  detalle_Unidad, name='unidad_detail'),
        url(r'unidades/(?P<asociacion_id>\d{1,5})/agregar/$', UnidadCreateView.as_view(), name='unidad_create'),
        url(r'unidades/(?P<asociacion_id>\d{1,5})/editar/(?P<pk>\d{1,5})/$', UnidadUpdateView.as_view(), name='unidad_update'),
        url(r'unidades/(?P<pk>\d{1,5})/baja/$', darBajaUnidad,name='unidad_baja'),
        url(r'unidades/exportar/CSV/$', exportarCSV,{"modelo": Unidad}, name='unidad_exportarCSV'),
        url(r'unidades/(?P<asociacion_id>\d{1,5})/exportar/XLS/$', exportar_xls,{"modelo": Unidad}, name='unidad_exportarXLS'),

        #ABM Padron Bomberos
        url(r'pb/(?P<asociacion_id>\d{1,5})/$', ListPadronBView.as_view(),name='pbomb_list'),
        url(r'pb/(?P<pk>\d{1,5})/detalle/$',  PadronBDetailView.as_view(), name='pbomb_detail'),
        url(r'pb/(?P<asociacion_id>\d{1,5})/agregar/$', PadronBCreateView.as_view(), name='pbomb_create'),
        url(r'pb/(?P<asociacion_id>\d{1,5})/editar/(?P<pk>\d{1,5})/$', PadronBUpdateView.as_view(), name='pbomb_update'),
        url(r'pb/(?P<asociacion_id>\d{1,5})/exportar/CSV/$', exportarCSV,{"modelo": PadronBomberos}, name='pbomb_exportarCSV'),
        url(r'pb/(?P<asociacion_id>\d{1,5})/exportar/XLS/$', exportar_xls_bomberos,name='pbomb_exportarXLS'),

        #ABM Padron Cadetes
        url(r'padron_cadetes/(?P<asociacion_id>\d{1,5})/$', ListPadronCView.as_view(),name='padron_cadetes_list'),
        url(r'padron_cadetes/(?P<pk>\d{1,5})/detalle/$',  PadronCDetailView.as_view(), name='padron_cadetes_detail'),
        url(r'padron_cadetes/(?P<asociacion_id>\d{1,5})/agregar/$', PadronCCreateView.as_view(), name='padron_cadetes_create'),
        url(r'padron_cadetes/(?P<asociacion_id>\d{1,5})/editar/(?P<pk>\d{1,5})/$', PadronCUpdateView.as_view(), name='padron_cadetes_update'),
        url(r'padron_cadetes/(?P<asociacion_id>\d{1,5})/exportar/CSV/$', exportarCSV,{"modelo": PadronCadetes}, name='padron_cadetesn_exportarCSV'),
        url(r'padron_cadetes/(?P<asociacion_id>\d{1,5})/exportar/XLS/$', exportar_xls_cadetes, name='padron_cadetes_exportarXLS'),

        # ABM Personas
        url(r'personas/(?P<pk>\d{1,5})/detalle/$',  PersonasDetailView.as_view(), name='personas_detail'),
        url(r'personas/agregar/$', PersonasCreateView.as_view(), name='personas_create'),
        url(r'personas/(?P<pk>\d{1,5})/editar/$', PersonasUpdateView.as_view(), name='personas_update'),
        url(r'personas/(?P<pk>\d{1,5})/baja/$', darBajaPersona, name='personas_baja'),
        #url(r'personas/(?P<asociacion_id>\d{1,5})/exportar/CSV/$', exportarCSV,{"modelo": Persona}, name='personas_exportarCSV'),
        #url(r'personas/(?P<asociacion_id>\d{1,5})/exportar/XLS/$', exportar_xls,{"modelo": Persona}, name='asociacion_exportarXLS'),

)

sistema_bomberos/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib import admin
from bomberos.views import *
admin.autodiscover()

urlpatterns = patterns('',


    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'bomberos.views.login'),
    url(r'^logout/$', 'bomberos.views.logout'),
    url(r'^bomberos/', include('bomberos.urls')),
    url(r'^contacto/', include("contact_form.urls",namespace="contact_form")),
    url(r'^$', PrincipalView.as_view()),
    url(r'^cv/','bomberos.views.cv'),

)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

bomberos/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from utilidades import *
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

class Localidad(models.Model):
    localidad_id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)
    class Meta:
        db_table = u'Localidad'
        verbose_name_plural = "Localidades"
        ordering = ["-nombre"]
    def __unicode__(self):
        return u'%s' % (self.nombre)

class Provincia(models.Model):
    provincia_id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)
    class Meta:
        db_table = u'Provincia'
        verbose_name_plural = "Provincias"
    def __unicode__(self):
        return u'%s' % (self.nombre)

class Pais(models.Model):
    pais_id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)
    class Meta:
        db_table = u'Pais'
        verbose_name_plural = "Paises"
    def __unicode__(self):
        return u'%s' % (self.nombre)

class Persona(models.Model):
    persona_id = models.AutoField(primary_key=True)
    apellido = models.CharField(max_length=100)
    nombre = models.CharField(max_length=100)
    tipodoc = models.CharField('Tipo Documento',max_length=10,choices=TIPO_DOC,default=1)
    nrodoc = models.CharField('Número Documento',max_length=20)
    direccion = models.CharField(max_length=100, blank=True)
    telefono = models.CharField(max_length=45, blank=True)
    celular = models.CharField(max_length=45, blank=True)
    email = models.EmailField(max_length=45, blank=True)
    baja = models.BooleanField(default=False)

    class Meta:
        db_table = u'Persona'
        verbose_name_plural = "Personas"
    def __unicode__(self):
        return u'%s %s - %s: %s' % (self.apellido, self.nombre,self.tipodoc,self.nrodoc)

    def get_absolute_url(self):
    	return reverse('personas_detail', args=[self.pk])


class Asociacion(models.Model):
    asociacion_id = models.AutoField(primary_key=True)
    nro_asoc = models.CharField(max_length=10)
    nombre = models.CharField(max_length=20)
    nro_regional = models.CharField(max_length=10)
    direccion = models.CharField(max_length=100, blank=True)
    localidad = models.ForeignKey(Localidad, verbose_name = 'Localidad',related_name='+')
    provincia = models.ForeignKey(Provincia, verbose_name = 'Provincia',related_name='+')
    telefono1 = models.CharField(max_length=45, blank=True)
    telefono2 = models.CharField(max_length=45, blank=True)
    telefono3 = models.CharField(max_length=45, blank=True)
    email = models.EmailField(blank=True)
    fax = models.CharField(max_length=45, blank=True)
    presidente = models.ForeignKey(Persona, verbose_name = 'Presidente',related_name='+')
    jefe = models.ForeignKey('Bombero',limit_choices_to = {'es_cadete': False} ,verbose_name = 'Jefe',related_name='+')
    subjefe = models.ForeignKey('Bombero',limit_choices_to = {'es_cadete': False} ,verbose_name = 'Subjefe',related_name='+')
    baja = models.BooleanField(default=False)

    class Meta:
        db_table = u'Asociacion'
        verbose_name_plural = "Asociaciones"

    def get_absolute_url(self):
    	return reverse('asociacion_detail', args=[self.pk])

    def __unicode__(self):
        return u'%s - %s - %s' % (self.nro_asoc,self.nro_regional,self.nombre)


class Bombero(models.Model):
    bombero_id = models.AutoField(primary_key=True)
    asociacion = models.ForeignKey(Asociacion, verbose_name = 'Asociacion',related_name='+',null=True, blank=True)
    apellido = models.CharField(max_length=100)
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=100, blank=True)
    localidad = models.ForeignKey(Localidad, verbose_name = 'Localidad',related_name='+')
    provincia = models.ForeignKey(Provincia, verbose_name = 'Provincia',related_name='+')
    pais = models.ForeignKey(Pais, verbose_name = 'Pais',related_name='+')
    tipodoc = models.CharField('Tipo Documento',max_length=10,choices=TIPO_DOC,default=1)
    nrodoc = models.CharField('Número Documento',max_length=20)
    fecha_nac = models.DateField()
    lugar_nac = models.CharField(max_length=100, blank=True)
    estado_civil = models.CharField('Estado Civil',max_length=10,choices=TIPO_ESTADO_CIVIL,default=1)
    grupo_sanguineo = models.CharField('Grupo Sanguíneo',max_length=10,choices=TIPO_GS,default=1,blank=False)
    telefono = models.CharField(max_length=45, blank=True)
    celular = models.CharField(max_length=45, blank=True)
    email = models.EmailField(max_length=45, blank=True)
    observaciones = models.TextField(blank=True)
    foto= models.ImageField(blank=True, upload_to='imagenes')
    es_cadete = models.BooleanField(default=False)
    baja = models.BooleanField(default=False)
    class Meta:
        db_table = u'Bombero'
        verbose_name_plural = "Bomberos"


    def get_absolute_url(self):
    	return reverse('bombero_detail', args=[self.pk])

    def __unicode__(self):
        return u'%s %s - %s: %s' % (self.apellido, self.nombre,self.tipodoc,self.nrodoc)


class Grado(models.Model):
    grado_id = models.AutoField(primary_key=True)
    prioridad = models.PositiveIntegerField()
    descripcion = models.CharField(max_length=50)
    class Meta:
        db_table = u'Grado'
        verbose_name_plural = "Grados"
    def __unicode__(self):
        return u'%s' % (self.descripcion)

class Cargo(models.Model):
    cargo_id = models.AutoField(primary_key=True)
    prioridad = models.PositiveIntegerField()
    descripcion = models.CharField(max_length=50)
    class Meta:
        db_table = u'Cargo'
        verbose_name_plural = "Cargos"
    def __unicode__(self):
        return u'%s' % (self.descripcion)

class PadronBomberos(models.Model):
    padron_id = models.AutoField(primary_key=True)
    anio = models.PositiveIntegerField(verbose_name = 'Año')
    bombero = models.ForeignKey(Bombero,limit_choices_to = {'es_cadete': False}, verbose_name = 'Bombero Voluntario',related_name='+')
    asociacion = models.ForeignKey(Asociacion, verbose_name = 'Asociacion',related_name='+')
    credencial = models.CharField(max_length=50,
        validators=[
            RegexValidator(
                regex= '[0-9]{1,3}[-][0-9]{1,3}[-][R][0-9]{1,3}',
                message='La credencial debe ser del tipo [Nº Asoc.]-[Nº Bombero]-[R + Nº Regional]',
                code='invalid_credencial'
            ),
        ])

    grado =models.ForeignKey(Grado, verbose_name = 'Grado',related_name='+')
    cargo =models.ForeignKey(Cargo, verbose_name = 'Cargo',related_name='+')
    ultimo_ascenso = models.DateField(null=True, blank=True)
    fecha_ingreso = models.DateField(null=True, blank=False)
    iapos = models.BooleanField(default=False,blank=True)
    reincorporaciones = models.DateField(null=True, blank=True)
    observaciones = models.TextField(blank=True)

    class Meta:
        db_table = 'PadronBomberos'
        verbose_name_plural = "PadronBomberos"
        unique_together = ('anio', 'bombero','asociacion',)

    def get_absolute_url(self):
    	return reverse('pbomb_detail', args=[self.pk])

    def __unicode__(self):
        return u'%s' % (self.credencial)

    def clean(self):
        super(PadronBomberos, self).clean()

class PadronCadetes(models.Model):
    padron_id = models.AutoField(primary_key=True)
    anio = models.PositiveIntegerField(verbose_name = 'Año')
    bombero = models.ForeignKey(Bombero,limit_choices_to = {'es_cadete': True}, verbose_name = 'Bombero Voluntario',related_name='+')
    asociacion = models.ForeignKey(Asociacion, verbose_name = 'Asociacion',related_name='+')
    nivel = models.CharField('Nivel',max_length=10,choices=TIPO_NIVEL,default=1)#En el caso de los cadetes se le carga el nivel
    cargo =models.ForeignKey(Cargo, verbose_name = 'Cargo',related_name='+')
    ultimo_ascenso = models.DateField(null=True, blank=True)
    fecha_ingreso = models.DateField(null=True, blank=False)
    observaciones = models.TextField(blank=True)

    class Meta:
        db_table = u'PadronCadetes'
        verbose_name_plural = "PadronCadetes"
        unique_together = ('anio', 'bombero','asociacion',)

    def get_absolute_url(self):
        return reverse('padron_cadetes_detail', args=[self.pk])

    def __unicode__(self):
        return u'%s' % (self.bombero)

    def cadetesPorId(id):
        if not id:
            return self.objects.all()
        else:
            return self.objects.filter(asociacion__pk=id)

class Tipo_Vehiculo(models.Model):
    vehiculo_id = models.AutoField(primary_key=True)
    descripcion = models.CharField(max_length=50)
    class Meta:
        db_table = u'Tipo_Vehiculo'
        verbose_name_plural = "Tipo_Vehiculos"
    def __unicode__(self):
        return u'%s' % (self.descripcion)

class Tipo_Carroceria(models.Model):
    carroceria_id = models.AutoField(primary_key=True)
    descripcion = models.CharField(max_length=50)
    class Meta:
        db_table = u'Tipo_Carroceria'
        verbose_name_plural = "Tipo_Carrocerias"
    def __unicode__(self):
        return u'%s' % (self.descripcion)

class Tipo_Unidad(models.Model):
    tipo_unidad_id = models.AutoField(primary_key=True)
    descripcion = models.CharField(max_length=50)
    class Meta:
        db_table = u'Tipo_Unidad'
        verbose_name_plural = "Tipo_Unidades"
    def __unicode__(self):
        return u'%s' % (self.descripcion)

class Unidad(models.Model):
    unidad_id = models.AutoField(primary_key=True)
    asociacion = models.ForeignKey(Asociacion, verbose_name = 'Asociacion',related_name='+',null=True, blank=True)
    tipo_vehiculo = models.ForeignKey(Tipo_Vehiculo, verbose_name = 'Tipo Vehículo',related_name='+')
    tipo_carroceria = models.ForeignKey(Tipo_Carroceria, verbose_name = 'Tipo Carrocería',related_name='+')

templates/bomberos/asociacion_form.html
{% extends "base.html" %}
{% block extra_js %}
<script>
    $(function() {
        $( ".datePicker" ).datepicker(
            {
                dateFormat: "dd/mm/yy",
                readonly: "true",
                firstDay: 1,
                dayNamesMin: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa"],
                dayNamesShort: ["Dom", "Lun", "Mar", "Mie", "Jue", "Vie", "Sab"],
                monthNames:
                    ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio",
                    "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
                monthNamesShort:
                    ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul",
                    "Ago", "Sep", "Oct", "Nov", "Dic"],
            });
    });

   function msj(msg)
   {alert(msg);};

</script>
{% endblock %}
{% block main %}

<div class="list-group2">
        <a href="#" class="list-group-item active"><b>Agregar/Modificar datos de la Asociación</b></a>
        </div>

<div class="container">
<div class="row clearfix">
<form class="form-horizontal" action="" method="post" role="form" >
		<div class="col-md-6 ">
			{{ form.media }}
			{% for field in form %}{% csrf_token %}
			 <div class="form-group">
                              <div class="col-xs-4">
                                <label class="pull-right">{{field.label|title}}:</label>
                               </div>
                                <div class="col-xs-6">{{field}}
                                {% if field.field.required %}
                                    <em>*</em>
                                {% endif %}
                                {% if field.errors %}
                                 <div class="alert alert-danger">
                                 {{ field.errors }}
                                 </div>
                                {% endif %}
                                </div>
                             </div>
			{% endfor %}

				 <div class="form-group ">
				<input type="submit" class="btn btn-primary pull-right" value="{% if submit_text %} {{submit_text}} {%else%} Guardar {% endif %}"/>
				</div>
                    </div>
</form>
</div>
</div>

{% endblock%}

templates/bomberos/asociacion_list.html
{% extends "listado.html" %}
        {% block titulo %}
        <div class="list-group2">
        <a href="#" class="list-group-item active"><b>Listado de Asociaciones</b>
        <h5 class="pull-right">( {{asociacion|default_if_none:"Administrador"}} )</h5>
        </a>
        </div>
        {% endblock %}
	
	{% block acciones %}
	    <div class="opciones">
             <h3>Filtrado de Datos</h3>
                <a type="button" class="btn btn-primary boton"
                            href="{% url "asociaciones_list" %}agregar/" >
                            Agregar Nueva
                    </a>
                <div class="btn-group listado">
                  <button id="filtro_asoc" type="button" class="btn btn-primary dropdown-toggle filtro" data-toggle="dropdown">
                    {% if not user.get_profile.asociacion_id %}Filtrar por Asociación{% else %}Filtrar por Asociación{% endif %}
                    <b class="caret"></b>
                  </button>
                    <ul class="dropdown-menu" role="menu">
                     {% for asoc in asociaciones %}
                     <li><a val="{{asoc}}" href="{% url "asociaciones_list" %}{{asoc.pk}}/">{{asoc}}</a></li>
                     {% endfor %}
                     {% if not user.get_profile.asociacion_id %}
                      <li><a href="{% url "asociaciones_list" %}" val="0">Todas </a></li>
                     {% endif %}
                    </ul>

                </div>
                <h3>Exportación de Datos</h3>
                 <a type="button" class="btn btn-primary boton"
                     {% if asociacion %}href="{% url "asociaciones_list" %}{{asociacion.pk}}/exportar/XLS/"{% endif %}>XLS</a>
            </div>
	
	{% endblock %}
	
	{% block table_heading %}
		<th>Id</th>
                  <th>Número</th>
                  <th>Nombre</th>
		<th>Regional</th>
		<th>Dirección</th>
		<th>Localidad</th>
		<th>Presidente</th>
		<th>Jefe</th>
		<th>Subjefe</th>
	{% endblock %}

	{% block item_iteration_row %}
		<td>{% if user.is_authenticated %}
		<a href="{{ item.get_absolute_url }}" target="_blank" onClick="window.open(this.href, this.target, 'width=500,height=450'); return false;"><span class="label label-primary">{{item.pk}}</span></a>
		{% endif %}
		</td>
		<td>{{ item.nro_asoc }}</td>
		<td>{{ item.nombre }}</td>
		<td>{{ item.nro_regional }}</td>
		<td>{{ item.direccion }}</td>
		<td>{{ item.localidad }} ({{ item.provincia }})</td>
		<td>{{ item.presidente}}</td>
		<td>{{ item.jefe }}</td>
		<td>{{ item.subjefe }}</td>
  	{% endblock %}
  	
        {% block botones_edicion_fila %}
		{% if user.is_authenticated %}
			<a class="glyphicon glyphicon-edit" href="/bomberos/asociaciones/{{item.pk}}/editar/"></a>
		{% endif %}
         {% endblock %}

templates/bomberos/bombero_detail.html
<head>
{% load static from staticfiles %}
 <link rel="stylesheet" href="{% static 'css/estilo.css' %}" type="text/css" />
</head>
<body>

<div class="row">
    <h2>Detalles del Bombero <span class="red">{{ bomberos.pk }}</span></h2>
            <p><label class="control-label">Apellido y Nombre: </label> {{bomberos.apellido|title}} {{bomberos.nombre|title}}</p>
            <p><label class="control-label">Tipo y Nro. de Documento: </label>{{bomberos.get_tipodoc_display}} {{bomberos.nrodoc}}</p>
            <p><label class="control-label">Dirección: </label>{{bomberos.direccion|title}} - {{bomberos.localidad|title}} - {{bomberos.provincia|title}}</p>
            <p><label class="control-label">Fecha Nacimiento: </label>{{bomberos.fecha_nac}}</p>
            <img src="{% if bomberos.foto %}{{ bomberos.foto.url }} {% endif %}" />
</div>

</body>

templates/bomberos/bombero_list.html
{% extends "listado.html" %}
{% load static from staticfiles %}
        {% block titulo %}
        <div class="list-group2">
        <a href="#" class="list-group-item active">
            <b>Listado Completo del Cuerpo de Bomberos</b>
            <h5 class="pull-right">( {{asociacion|default_if_none:"Administrador"}} )</h5>
        </a>
        </div>
        {% endblock %}
	
	{% block acciones %}
            <div class="opciones">
             <h3>Filtrado de Datos</h3>

                <a type="button" class="btn btn-primary boton"
                            href="{% url "bomberos_list" %}{% if not asociacion %}0/{% else %}{{asociacion.pk}}/{% endif %}agregar/" >
                            Agregar Nuevo
                    </a>
                <div class="btn-group listado">
                  <button id="filtro_asoc" value="Filtrar por Asociación" type="button" class="btn btn-primary dropdown-toggle filtro" data-toggle="dropdown">
                    Filtrar por Asociación
                    <b class="caret"></b>
                  </button>
                    <ul class="dropdown-menu" role="menu">
                     {% for asoc in asociaciones %}
                     <li><a val="{{asoc}}" href="{% url "bomberos_list" %}{{asoc.pk}}/">{{asoc}}</a></li>
                     {% endfor %}
                     {% if not user.get_profile.asociacion_id %}
                      <li><a href="{% url "bomberos_list" %}" val="0">Todas </a></li>
                     {% endif %}
                    </ul>
                </div>
                <h3>Exportación de Datos</h3>
                 <a type="button" class="btn btn-primary boton"
                     {% if asociacion %}href="{% url "bomberos_list" %}{{asociacion.pk}}/exportar/XLS/"{% endif %}>XLS</a>

            </div>
	{% endblock %}
	
	{% block idTabla %}tabla_bomberos{% endblock %}

	{% block table_heading %}
		<th>Id</th>
                  <th>Apellido</th>
		<th>Nombre</th>
		<th>Dirección</th>
		<th>Asociación</th>
		<th>Cadete</th>
		<th>Localidad</th>
		<th>Provincia</th>
		<th>Documento</th>
		<th>Fecha Nac.</th>
		<th>Estado Civil</th>

	{% endblock %}

	{% block item_iteration_row %}
		<td>{% if user.is_authenticated %}
		<a href="{{ item.get_absolute_url }}" target="_blank" onClick="window.open(this.href, this.target, 'width=500,height=450'); return false;"><span class="label label-primary">{{item.pk}}</span></a>
		{% endif %}
		</td>
		<td>{{ item.apellido }}</td>
		<td>{{ item.nombre }}</td>
		<td>{{ item.direccion }}</td>
		<td>{{ item.asociacion|default_if_none:"Sin Asignar" }}</td>
		<td>{{ item.es_cadete|yesno:"Si,No" }}</td>
		<td>{{ item.localidad }}</td>
		<td>{{ item.provincia }}</td>
		<td>{{ item.tipodoc }} {{ item.nrodoc }}</td>
		<td>{{ item.fecha_nac|date:"d/m/Y" }}</td>
		<td>{{ item.get_estado_civil_display }}</td>

  	{% endblock %}
  	
  	{% block botones_edicion_fila %}
		{% if user.is_authenticated %}
			<a class="glyphicon glyphicon-edit" href="/bomberos/bomberos/{% if not asociacion %}0/{% else %}{{asociacion.pk}}/{% endif %}editar/{{item.pk}}/"></a>
			<a class="glyphicon glyphicon-trash" href="{% url "bombero_baja" item.pk %}"></a>
		{% endif %}
         {% endblock %}
{% block extra_js %}
<script>	



    TableTools.DEFAULTS.aButtons = [ "copy", "csv", "xls", "pdf" ];
    TableTools.DEFAULTS.sSwfPath = "{% static 'datatables/media/swf/copy_csv_xls_pdf.swf' %}";

     $('#tabla_bomberos').dataTable({
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "sDom": 'T<"clear">lfrtip',
            "aaSorting":[],
            });
</script>	
{% endblock %}